[package]
name = "timely_logging"
version = "0.0.1"

description = "Logging infrastructure for timely dataflow"

[features]
default=[]

[dependencies]
abomonation = { git = "https://github.com/frankmcsherry/abomonation" }
abomonation_derive = { git = "https://github.com/mystor/abomonation_derive.git" }
byteorder="0.4.2"
getopts="0.2.14"
time="0.1.34"
