[package]
name = "timely_logging"
version = "0.0.1"

description = "Logging infrastructure for timely dataflow"

[features]
logging=[]
default=[] # ["logging"]

[dependencies]
abomonation="0.4.4"
abomonation_derive = "0.1.2"
byteorder="0.4.2"
getopts="0.2.14"
time="0.1.34"
