[package]
name = "timely_communication"
version = "0.1.8"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "Communication layer for timely dataflow"

# These URLs point to more information about the repository
documentation = "https://frankmcsherry.github.com/timely-dataflow"
homepage = "https://github.com/frankmcsherry/timely-dataflow"
repository = "https://github.com/frankmcsherry/timely-dataflow.git"
keywords = ["timely", "dataflow"]
license = "MIT"

[dependencies.abomonation]
git="https://github.com/frankmcsherry/abomonation"

[features]
logging=[]

[dependencies]
byteorder="0.4.2"
getopts="0.2.14"

opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
time="0.1.34"
